### ISSUE TITLE
Test that file I/O is unbuffered

### ISSUE THREAD

**Issue by sunfishcode** [CraneStation/wasi-misc-tests#11]
As discussed in https://github.com/CraneStation/wasmtime/issues/255, we should test that `fd_write` writing to files is unbuffered. The way to do that is to open the same file with `path_open` twice, and with one file handle write a single byte, and with the other read a single byte, and we should see the byte we just wrote.

**Comment by kubkon** [comment]
Thanks for reporting this, @sunfishcode. I’ll add the test case in as it was on my todo anyhow after CraneStation/wasmtime#255 :-)
